/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Contract {
  schema_version: "2.0.0";
  generated_at: string;
  meta: {
    feeds: FeedHealth[];
  };
  events: CrisisEvent[];
}
export interface FeedHealth {
  source: "usgs" | "gdacs";
  window: "all_day" | "significant_week" | "events4app";
  status: "ok" | "error";
  fetched_at: string;
  event_count: number;
  error?: string | null;
}
export interface CrisisEvent {
  id: string;
  hazard: "EQ" | "TC" | "FL" | "VO" | "DR";
  title: string;
  place: string;
  time: string;
  geometry: Geometry;
  magnitude: number | null;
  severity: Severity;
  major: boolean;
  provisional: boolean;
  /**
   * @minItems 1
   */
  sources: [FeedSource, ...FeedSource[]];
  affected: Affected;
}
export interface Geometry {
  lat: number;
  lon: number;
  depth_km?: number | null;
}
export interface Severity {
  level: "minor" | "moderate" | "serious" | "severe";
  score: number;
  inputs: SeverityInputs;
  boost: SeverityBoost;
}
export interface SeverityInputs {
  mag: number | null;
  sig: number | null;
  alert: "green" | "yellow" | "orange" | "red" | null;
  alert_score: number | null;
}
export interface SeverityBoost {
  nearest_place: string | null;
  population: number | null;
  distance_km: number | null;
  applied: number;
}
export interface FeedSource {
  feed: "usgs" | "gdacs";
  id: string;
  url: string;
}
export interface Affected {
  estimate: number | null;
  basis: string;
  source: "gdacs" | null;
}
