/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Contract {
  schema_version: "1.0.0";
  generated_at: string;
  meta: {
    feeds: FeedHealth[];
  };
  events: CrisisEvent[];
}
export interface FeedHealth {
  source: "usgs";
  window: "all_day" | "significant_week";
  status: "ok" | "error";
  fetched_at: string;
  event_count: number;
  error?: string;
}
export interface CrisisEvent {
  id: string;
  hazard: "EQ";
  title: string;
  place: string;
  time: string;
  geometry: Geometry;
  magnitude: number;
  severity: Severity;
  major: boolean;
  provisional: boolean;
  /**
   * @minItems 1
   */
  sources: [FeedSource, ...FeedSource[]];
}
export interface Geometry {
  lat: number;
  lon: number;
  depth_km?: number | null;
}
export interface Severity {
  level: "minor" | "moderate" | "serious" | "severe";
  inputs: {
    mag: number;
    sig: number | null;
    alert: "green" | "yellow" | "orange" | "red" | null;
  };
}
export interface FeedSource {
  feed: "usgs";
  id: string;
  url: string;
}
